<a href="https://colab.research.google.com/github/ze-16/Speech-training-agent/blob/main/Speech_training_agent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import os
import gdown
import torch
from transformers import BertTokenizer, BertModel
from torch.utils.data import TensorDataset, DataLoader
import torch.nn as nn
from torch.optim import AdamW
from transformers import get_linear_schedule_with_warmup
from transformers import Wav2Vec2Model, Wav2Vec2FeatureExtractor
import timeit
import shutil
import torchaudio
from huggingface_hub.utils import disable_progress_bars
from transformers import logging as hf_logging
import tqdm, tqdm.auto, tqdm.std

solves github push errors because of widgets

In [2]:
os.environ["HF_HUB_DISABLE_PROGRESS_BARS"] = "1"
disable_progress_bars()
hf_logging.set_verbosity_error()
tqdm.auto.tqdm = tqdm.std.tqdm
tqdm.auto.trange = tqdm.std.trange

# **Text-only sub-system**



---



---

In [3]:
# Coding the file path and allowing access through link
file_id = '1mC-mj6zuojm8jWRBH46Vj2Gno1ZsXlRF'
url = f'https://drive.google.com/uc?id={file_id}'
output = 'Text_data.csv'

In [4]:
# If statement to make sure file is only downloaded once and not repeatedly
if not os.path.exists(output):
    print("Downloading file...")
    gdown.download(url, output, quiet=False)
else:
    print(f"File already exists.")

Downloading file...

Downloading...
From: https://drive.google.com/uc?id=1mC-mj6zuojm8jWRBH46Vj2Gno1ZsXlRF
To: /content/Text_data.csv
100%|██████████| 14.2M/14.2M [00:00<00:00, 141MB/s]

In [5]:
# Loading the goemotions_2 dataset for EDA
df = pd.read_csv(output)

In [6]:
# Loading the dimensions of the dataset
df.shape

(70000, 37)

In [7]:
# Loading the first 10 values of the dataset to explore what the data looks like
df.head(10)

,text,id,author,subreddit,link_id,parent_id,created_utc,rater_id,example_very_unclear,admiration,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
0,We can hope,ee3o3ko,darkenseyreth,EdmontonOilers,t3_ag4r9j,t1_ee3mhad,1.547529e+09,62,False,0,...,0,0,1,0,0,0,0,0,0,0
1,Shhh don't give them the idea!,eebl3z7,BoinkBoinkEtAliae,MurderedByWords,t3_ah3o76,t1_eeb68lo,1.547777e+09,76,False,0,...,0,0,0,0,0,0,0,0,0,0
2,"Thank you so much, kind stranger. I really nee...",ed4fe9l,savageleaf,raisedbynarcissists,t3_abwh00,t1_ed4etbj,1.546482e+09,24,False,0,...,0,0,0,0,0,0,0,0,0,0
3,Ion know but it would be better for you to jus...,efavtdu,CADDiLLXC,darknet,t3_al4njw,t3_al4njw,1.548800e+09,62,False,0,...,0,0,0,0,0,0,0,0,0,1
4,I'm honestly surprised. We should have fallen ...,ee2imz2,CorporalThornberry,CollegeBasketball,t3_afxt6t,t1_ee22nyr,1.547497e+09,55,False,0,...,0,0,0,0,0,0,0,0,0,0
5,Jurisprudence fetishist gets off on technicality.,ednv5fy,100Gold,TopMindsOfReddit,t3_ae3p1m,t1_ednn3pz,1.547068e+09,12,False,0,...,0,0,0,0,0,0,0,0,0,1
6,One of my worst nightmares. Ugh.,ed60o6e,June1111,ExpectationVsReality,t3_ac7y4f,t3_ac7y4f,1.546541e+09,55,False,0,...,0,0,0,0,0,0,0,0,0,0
7,Is this real? 🤔,edjldcm,Uneekusername101,instant_regret,t3_adr232,t3_adr232,1.546928e+09,72,False,0,...,0,0,0,0,0,0,0,0,0,0
8,My favorite pod when they are fresh & clear. S...,ee7j34k,_BAMBOOZLE_,juul,t3_agn37x,t3_agn37x,1.547662e+09,12,False,0,...,0,0,0,0,0,0,0,0,0,1
9,I get wound up over completely imagined conver...,eeztbjr,TheLiquidSquid,aspergers,t3_ajpzf0,t1_eeypbzh,1.548483e+09,61,False,0,...,0,0,1,0,1,0,0,0,0,0

In [8]:
# Check the names of the headings and explore their data-types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 37 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   text                  70000 non-null  object
 1   id                    70000 non-null  object
 2   author                70000 non-null  object
 3   subreddit             70000 non-null  object
 4   link_id               70000 non-null  object
 5   parent_id             70000 non-null  object
 6   created_utc           70000 non-null  float64
 7   rater_id              70000 non-null  int64
 8   example_very_unclear  70000 non-null  bool
 9   admiration            70000 non-null  int64
 10  amusement             70000 non-null  int64
 11  anger                 70000 non-null  int64
 12  annoyance             70000 non-null  int64
 13  approval              70000 non-null  int64
 14  caring                70000 non-null  int64
 15  confusion             70000 non-null  int64
 16  curiosity             70000 non-null  int64
 17  desire                70000 non-null  int64
 18  disappointment        70000 non-null  int64
 19  disapproval           70000 non-null  int64
 20  disgust               70000 non-null  int64
 21  embarrassment         70000 non-null  int64
 22  excitement            70000 non-null  int64
 23  fear                  70000 non-null  int64
 24  gratitude             70000 non-null  int64
 25  grief                 70000 non-null  int64
 26  joy                   70000 non-null  int64
 27  love                  70000 non-null  int64
 28  nervousness           70000 non-null  int64
 29  optimism              70000 non-null  int64
 30  pride                 70000 non-null  int64
 31  realization           70000 non-null  int64
 32  relief                70000 non-null  int64
 33  remorse               70000 non-null  int64
 34  sadness               70000 non-null  int64
 35  surprise              70000 non-null  int64
 36  neutral               70000 non-null  int64
dtypes: bool(1), float64(1), int64(29), object(6)
memory usage: 19.3+ MB

In [9]:
# Basic descriptive statistics for categorical variables
df.describe(include='object')

              text       id     author subreddit    link_id  parent_id
count        70000    70000      70000     70000      70000      70000
unique       43293    43448      37837       483      34995      41480
top     Thank you.  eep131n  [deleted]    cringe  t3_ae6ejj  t3_ae6ejj
freq            18        5       1236       295         35         25

In [10]:
# Checking for any missing values and their sum for each column
df.isna().sum()

text                    0
id                      0
author                  0
subreddit               0
link_id                 0
parent_id               0
created_utc             0
rater_id                0
example_very_unclear    0
admiration              0
amusement               0
anger                   0
annoyance               0
approval                0
caring                  0
confusion               0
curiosity               0
desire                  0
disappointment          0
disapproval             0
disgust                 0
embarrassment           0
excitement              0
fear                    0
gratitude               0
grief                   0
joy                     0
love                    0
nervousness             0
optimism                0
pride                   0
realization             0
relief                  0
remorse                 0
sadness                 0
surprise                0
neutral                 0
dtype: int64

In [11]:
# Removing variables/columns that will be of no consequence to the result upon initial look
df = df.drop(columns=(['id','author','subreddit','link_id','parent_id','created_utc','rater_id','example_very_unclear']))

In [12]:
# Running a check to make sure the targetted columns have been removed
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 29 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   text            70000 non-null  object
 1   admiration      70000 non-null  int64
 2   amusement       70000 non-null  int64
 3   anger           70000 non-null  int64
 4   annoyance       70000 non-null  int64
 5   approval        70000 non-null  int64
 6   caring          70000 non-null  int64
 7   confusion       70000 non-null  int64
 8   curiosity       70000 non-null  int64
 9   desire          70000 non-null  int64
 10  disappointment  70000 non-null  int64
 11  disapproval     70000 non-null  int64
 12  disgust         70000 non-null  int64
 13  embarrassment   70000 non-null  int64
 14  excitement      70000 non-null  int64
 15  fear            70000 non-null  int64
 16  gratitude       70000 non-null  int64
 17  grief           70000 non-null  int64
 18  joy             70000 non-null  int64
 19  love            70000 non-null  int64
 20  nervousness     70000 non-null  int64
 21  optimism        70000 non-null  int64
 22  pride           70000 non-null  int64
 23  realization     70000 non-null  int64
 24  relief          70000 non-null  int64
 25  remorse         70000 non-null  int64
 26  sadness         70000 non-null  int64
 27  surprise        70000 non-null  int64
 28  neutral         70000 non-null  int64
dtypes: int64(28), object(1)
memory usage: 15.5+ MB

In [13]:
# Upon further reflection, dictionary created to condense the range of emotions, for the sake of simplicity of providing feedback at project end
emotion_groups = {
    'anger': ['anger', 'annoyance', 'disapproval', 'disgust', 'fear', 'nervousness'],
    'joy': ['joy', 'admiration', 'amusement', 'approval', 'caring', 'desire',
            'excitement', 'gratitude', 'love', 'optimism', 'pride', 'relief'],
    'sadness': ['sadness', 'disappointment', 'embarrassment', 'grief', 'remorse'],
    'neutral': ['neutral', 'confusion', 'curiosity', 'realization', 'surprise']
}

In [14]:
# Function that helps map the 28 emotions into 4 core groups, in order of priority
def get_core_emotion(row):
  for col in emotion_groups['anger']:
        if row[col] == 1:
            return 'anger'

  for col in emotion_groups['sadness']:
        if row[col] == 1:
            return 'sadness'

  for col in emotion_groups['joy']:
        if row[col] == 1:
            return 'joy'

  return 'neutral'

In [15]:
# Applying the above function onto the dataset
df['core_emotion'] = df.apply(get_core_emotion, axis=1)

In [16]:
# Checking to see the distribution of each category
df['core_emotion'].value_counts()

core_emotion
neutral    26126
joy        25520
anger      12900
sadness     5454
Name: count, dtype: int64

In [17]:
# Writing the new organised emotions into a new csv file
df[['text', 'core_emotion']].to_csv('Text_data2.csv', index=False)

In [18]:
# Loading the new file and checking if the mapping worked
df = pd.read_csv('Text_data2.csv')
df.head()

                                                text core_emotion
0                                        We can hope          joy
1                     Shhh don't give them the idea!        anger
2  Thank you so much, kind stranger. I really nee...          joy
3  Ion know but it would be better for you to jus...      neutral
4  I'm honestly surprised. We should have fallen ...          joy

In [19]:
# Checking to see the distribution of each category
df['core_emotion'].value_counts()

core_emotion
neutral    26126
joy        25520
anger      12900
sadness     5454
Name: count, dtype: int64

In [20]:
# Mapping the data to integers for the model.
label_map = {'neutral': 0, 'joy': 1, 'sadness': 2, 'anger': 3}
df['core_emotion'] = df['core_emotion'].map(label_map)

In [21]:
# Loading a pre-trained bert tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [22]:
# Function to tokenize raw text data for BERT
def TokenizetoBERT(dataframe, tokenizer, max_len=128):
  # Loading the data and labelling in regards to tensors
  text = dataframe['text'].tolist()
  labels = dataframe['core_emotion']
  labels_tensor = torch.tensor(dataframe['core_emotion'].values)

  # Tokenize
  tokenizing = tokenizer(
      text,
      add_special_tokens=True,
      max_length=max_len,
      padding='max_length',
      truncation=True,
      return_attention_mask=True,
      return_tensors='pt',
  )

  # Getting the tensors
  input_ids = tokenizing['input_ids']
  attention_masks = tokenizing['attention_mask']

  # Returning the tensors
  return input_ids, attention_masks, labels_tensor

In [23]:
# Splitting the data based on variable 'core_emotion'
train_set,test_set = train_test_split(df,test_size=0.3, random_state=14,stratify=df['core_emotion'])

In [24]:
# Using the previously defined function to tokenize
train_input, train_mask, train_label = TokenizetoBERT(train_set, tokenizer)
test_input, test_mask, test_label = TokenizetoBERT(test_set, tokenizer)

# Turning tensors into tuples using tensordataset (imprortant clarification)
train_dataset = TensorDataset(train_input, train_mask, train_label)
test_dataset = TensorDataset(test_input, test_mask, test_label)

In [25]:
# Using the built in DataLoader class from pytorch
train_loader=DataLoader(train_dataset,batch_size=64,shuffle=True,num_workers=2,pin_memory=True)
test_loader=DataLoader(test_dataset,batch_size=64,num_workers=2,pin_memory=True)

In [26]:
# Initialising BERT in order to check for configurations
bert = BertModel.from_pretrained('bert-base-uncased')

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 2407.44it/s, Materializing param=pooler.dense.weight]

In [27]:
# Checking for configurations for BERT
config = bert.config
print(config)

BertConfig {
  "add_cross_attention": false,
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": null,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "is_decoder": false,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "tie_word_embeddings": true,
  "transformers_version": "5.0.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

In [28]:
# Deleting BERT and config and cleaning up memory
del bert
del config
torch.cuda.empty_cache()

In [29]:
# Configuring BERT model to my choice using a python class
class BERTClassifier(nn.Module):
  def __init__(self, n_classes):
    super(BERTClassifier, self).__init__()

    self.bert = BertModel.from_pretrained('bert-base-uncased')

    self.drop = nn.Dropout(p=0.3)

    self.dim_reduction = nn.Linear (768,32)

    self.activation = nn.ReLU()

    # Defining the final classifier
    self.classifier = nn.Linear (32,n_classes)

  def forward(self, input_ids, attention_mask):
        # Feeding tokenized text into BERT
        outputs = self.bert(
            input_ids=input_ids,
            attention_mask=attention_mask
        )

        pooled_outputs = outputs.pooler_output
        output = self.drop(pooled_outputs)

        reduced = self.dim_reduction(output)
        reduced = self.activation(reduced)

        # Making the final prediction
        return self.classifier(reduced)

In [30]:
# Checking whether colab is utilising CPU or GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Creating instance of previous defined class/initialising the model and feeding n_classes=4 as a parameter
model = BERTClassifier(n_classes=4)

# Transfers the model to "device"/GPU
model = model.to(device)

# Compiling the model for increasing training speed
model = torch.compile(model)

Using device: cuda

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 3179.33it/s, Materializing param=pooler.dense.weight]

In [31]:
# Setting the optimizer with learning rate 3x10^-5
optimizer = AdamW(model.parameters(), lr=3e-5)


# Setting the weights of each class depending on the ratios between classes
weights = torch.tensor([1.0, 1.0, 2.0, 1.5]).to(device)

# Pre defined function calculating the loss using the weights defined above
loss_fn = nn.CrossEntropyLoss(weight=weights)

In [32]:
# Defining the number of epochs (training iterations) and variable to store the accuracy for each epoch
epochs = 3
best_accuracy = 0

In [33]:
# Scheduler to help slow down the learning rate during training
scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=0,
    num_training_steps=len(train_loader)*epochs
)

In [34]:
# Function defined for the training loop
def train_loop(train_loader, model, optimizer, loss_fn,scheduler):
    size = len(train_loader.dataset)

    # Switching the model to training mode
    model.train()


    # Loop to make predictions and adjust weights
    for i, batch in enumerate(train_loader):
        input_ids = batch[0].to(device)
        attention_mask = batch[1].to(device)
        labels = batch[2].to(device)

        # Making predictions
        pred = model(input_ids, attention_mask)
        loss = loss_fn(pred, labels)

        # Back propogating and adjusting gradients
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        # Adding scheduler step so the learning rate slows during trainign to prevent overfitting
        scheduler.step()

        if i % 300 == 0:
          loss, current = loss.item(), i * train_loader.batch_size + len(input_ids)
          print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

In [35]:
# Function defined for the testing loop
def test_loop(test_loader, model, loss_fn):

    # Switching model to evaluation mode
    model.eval()
    size = len(test_loader.dataset)
    num_batches = len(test_loader)
    test_loss, correct = 0, 0

    # Evaluating the model, no gradients are calculated
    with torch.no_grad():
        for batch in test_loader:

            input_ids = batch[0].to(device)
            attention_mask = batch[1].to(device)
            labels = batch[2].to(device)

            # Making predictions
            pred = model(input_ids,attention_mask)
            test_loss += loss_fn(pred, labels).item()
            correct += (pred.argmax(1) == labels).type(torch.float).sum().item()

    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")
    return correct

In [36]:
# Single most useful line of code in terms of training speed, using A100 gpu and batch size of 64, it brought training time down from ~14m to ~4m
torch.set_float32_matmul_precision('high')

In [37]:
# Loop to train and test through epochs
x = input().lower()
weight_id = '1ezXdVCEJ--Y_pQFsa0DohIgX4XNklhMH'
url = f'https://drive.google.com/uc?id={weight_id}'
weight = 'best_Weights.pth'
if x == 'y':
  start = timeit.default_timer()
  for t in range(epochs):
      print(f"Epoch {t+1}\n-------------------------------")
      train_loop(train_loader, model, optimizer, loss_fn,scheduler)
      current_accuracy = test_loop(test_loader, model, loss_fn)

      # Save best model
      if current_accuracy > best_accuracy:
          best_accuracy = current_accuracy
          torch.save(model.state_dict(), 'best_model_weights.pth')
          print(f"Saved best model weights with accuracy: {(100*best_accuracy):>0.1f}%")

  print("Done!")
  end = timeit.default_timer()
  print(f"Total time taken: {end - start}")
elif x == 'n' and not os.path.exists(weight):
    print("Downloading weights...")
    gdown.download(url, weight, quiet=False)
    model.load_state_dict(torch.load(weight))

else:
    print(f"File already exists.")

n
Downloading weights...

Downloading...
From (original): https://drive.google.com/uc?id=1ezXdVCEJ--Y_pQFsa0DohIgX4XNklhMH
From (redirected): https://drive.google.com/uc?id=1ezXdVCEJ--Y_pQFsa0DohIgX4XNklhMH&confirm=t&uuid=20d2cede-e4ad-40c8-869d-566536b772cf
To: /content/best_Weights.pth
100%|██████████| 438M/438M [00:02<00:00, 191MB/s]

# **Audio sub-system**



---



---

In [38]:
# Initialising the feature extractor for wav2vec2
feature_extractor = Wav2Vec2FeatureExtractor.from_pretrained("superb/wav2vec2-base-superb-er")

In [39]:
# Building a class for audio processing, using a variant of wav2vec2 speciic for 4 emotion classification
class Wav2Model (nn.Module):
  def __init__(self):
    super(Wav2Model, self).__init__()

    # Initialising the model with the pretrained weights
    self.wav2vec2 = Wav2Vec2Model.from_pretrained("superb/wav2vec2-base-superb-er")

    for param in self.wav2vec2.parameters():
      param.requires_grad = False

    # Unfreezing final 2 layers
    for l in self.wav2vec2.encoder.layers[-2:]:
      for param in l.parameters():
        param.requires_grad = True


    self.dim_reduction = nn.Linear(768, 32)

    self.activation = nn.ReLU()

  def forward(self, input_values):
    # With torch.no_grad because I will not be adjusting the gradients
    outputs = self.wav2vec2(input_values)
    pooled_outputs = outputs.last_hidden_state.mean(dim=1)

    output = self.dim_reduction(pooled_outputs)
    output = self.activation(output)
    return output

In [40]:
# Test case just to check if the model is working
wav_model = Wav2Model()

dummy_input = torch.randn(1, 16000)

output = wav_model(dummy_input)

print(f"Input shape: {dummy_input.shape}")
print(f"Output shape: {output.shape}")

if output.shape == (1, 32):
    print("Test passed! Output dimension is 32.")
else:
    print(f"Unexpected output shape: {output.shape}")

Loading weights: 100%|██████████| 211/211 [00:00<00:00, 3119.42it/s, Materializing param=masked_spec_embed]

Input shape: torch.Size([1, 16000])
Output shape: torch.Size([1, 32])
Test passed! Output dimension is 32.

# **Fusion System**



---



---

In [41]:
# Defining the fusion model as a class
class FusionModel(nn.Module):
  def __init__(self, wav_model, model, num_classes=4):
      super(FusionModel, self).__init__()
      # Fusion model includes instances of previously trained models and final classifier head
      self.WavModel = wav_model
      self.BertModel = model

      self.drop = nn.Dropout(p=0.3)

      self.classifier = nn.Linear(64, num_classes)

# Forward pass manual steps for BERT, extracted output for wav2vec2
  def forward(self, input_values, input_ids, attention_mask):
      outputs_bert = self.BertModel.bert(
          input_ids=input_ids,
          attention_mask=attention_mask
      )
      pooled_bert = outputs_bert.pooler_output
      reduced_bert = self.BertModel.drop(pooled_bert)
      reduced_bert = self.BertModel.dim_reduction(reduced_bert)
      reduced_bert = self.BertModel.activation(reduced_bert)

      reduced_wav = self.WavModel(input_values)

      # Final concatenation step before classification
      concat_outputs = torch.cat((reduced_bert, reduced_wav), dim=1)
      concat_outputs = self.drop(concat_outputs)

      return self.classifier(concat_outputs)

Loading the csv and wav files for IEMOCAP

In [42]:
iemocap_path = "/content/drive/MyDrive/IEMOCAP_Cleaned_Data"
iemocap_output_local = "/content/IEMOCAP_sorted"

In [43]:
if not os.path.exists(iemocap_output_local):
    shutil.copytree(iemocap_path,iemocap_output_local)
    print("iemocap data copied")
else:
  print("iemocap data already copied")

iemocap data copied

In [44]:
label_sent_path = os.path.join(iemocap_output_local,"label_sentence_data.csv")
wav_path = os.path.join(iemocap_output_local,"wavs")

In [45]:
iemo_csv = pd.read_csv(label_sent_path)

In [46]:
iemo_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7382 entries, 0 to 7381
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Recording_name  7382 non-null   object
 1   Emotion         7382 non-null   int64
 2   Sentence        7382 non-null   object
dtypes: int64(1), object(2)
memory usage: 173.1+ KB

In [47]:
# Checking for missing values correctly
iemo_csv.isnull().sum()

Recording_name    0
Emotion           0
Sentence          0
dtype: int64

In [48]:
# Splitting the data based on variable 'Emotion'
train_iemo,test_iemo = train_test_split(iemo_csv,test_size=0.3, random_state=14,stratify=iemo_csv['Emotion'])

In [49]:
# Custom dataset class to process (tokenize/feature extract) the data for the models
class CustomMultimodalDataset(torch.utils.data.Dataset):
  def __init__(self, dataframe, tokenizer, feature_extractor, wav_path,max_len = 128):
    self.dataframe = dataframe
    self.tokenizer = tokenizer
    self.feature_extractor = feature_extractor
    self.wav_path = wav_path
    self.max_len = max_len

  def __len__(self):
    return len(self.dataframe)

  def __getitem__(self, index):
    # Text
    row = self.dataframe.iloc[index]['Sentence']
    tokenizing = self.tokenizer(row, add_special_tokens = True, max_length = self.max_len,
                                padding = 'max_length', truncation = True,
                                return_attention_mask = True, return_tensors = 'pt')
    input_ids = tokenizing['input_ids'].squeeze()
    attention_mask = tokenizing['attention_mask'].squeeze()

    # Audio
    recording_name = self.dataframe.iloc[index]['Recording_name']
    recording = os.path.join(self.wav_path, recording_name + '.wav')

    wavform, sample_rate = torchaudio.load(recording)
    wavform = wavform.squeeze()
    input_values = self.feature_extractor(wavform, sampling_rate=16000, return_tensors="pt")['input_values'].squeeze()
    emo_label = self.dataframe.iloc[index]['Emotion']

    emo_tensor = torch.tensor(emo_label, dtype = torch.long)

    return input_ids, attention_mask, input_values, emo_tensor

In [50]:
# Custom collate function to pad ensuring the same dimensions specifically for the audio
def collate_fn(batch):

  input_ids, attention_mask, input_values, emo_tensor = zip(*batch)

  input_ids__stack = torch.stack(input_ids)
  attention_mask__stack = torch.stack(attention_mask)
  emo_tensor__stack = torch.stack(emo_tensor)

  audio_pad = torch.nn.utils.rnn.pad_sequence(input_values, batch_first=True)

  return input_ids__stack, attention_mask__stack, audio_pad, emo_tensor__stack

In [51]:
# Code re-used and adapted
# Function defined for the training loop
def train_loop_fusion(train_loader, model, optimizer, loss_fn, scheduler):
    size = len(train_loader.dataset)

    # Switching the model to training mode
    model.train()


    # Loop to make predictions and adjust weights
    for i, batch in enumerate(train_loader):
        input_ids = batch[0].to(device)
        attention_mask = batch[1].to(device)
        audio_pad = batch[2].to(device)
        emo_tensor = batch[3].to(device)

        # Making predictions
        pred = model(audio_pad, input_ids,attention_mask)
        loss = loss_fn(pred, emo_tensor)

        # Back propogating and adjusting gradients
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        # Adding scheduler step so the learning rate slows during trainign to prevent overfitting
        scheduler.step()

        if i % 300 == 0:
          loss_val, current = loss.item(), i * train_loader.batch_size + len(input_ids)
          print(f"loss: {loss_val:>7f}  [{current:>5d}/{size:>5d}]")

In [52]:
# Code re-used and adapted
# Function defined for the testing loop
def test_loop_fusion(test_loader, model, loss_fn):

    # Switching model to evaluation mode
    model.eval()
    size = len(test_loader.dataset)
    num_batches = len(test_loader)
    test_loss, correct = 0, 0

    # Evaluating the model, no gradients are calculated
    with torch.no_grad():
        for batch in test_loader:

            input_ids = batch[0].to(device)
            attention_mask = batch[1].to(device)
            audio_pad = batch[2].to(device)
            emo_tensor = batch[3].to(device)

            # Making predictions
            pred = model(audio_pad,input_ids,attention_mask)
            test_loss += loss_fn(pred, emo_tensor).item()
            correct += (pred.argmax(1) == emo_tensor).type(torch.float).sum().item()

    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")
    return correct

In [53]:
# Loading the weights for BERT
if os.path.exists('best_model_weights.pth'):
  print("Loading newly trained BERT weights")
  model.load_state_dict(torch.load('best_model_weights.pth'))
elif os.path.exists(weight):
  print("Loading the previously downloaded old weights.")
  model.load_state_dict(torch.load(weight))
else:
  print("Downloading weights...")

Loading the previously downloaded old weights.

In [54]:
# Create custom dataset instances
train_data_fusion = CustomMultimodalDataset(train_iemo, tokenizer, feature_extractor, wav_path)
test_data_fusion = CustomMultimodalDataset(test_iemo, tokenizer, feature_extractor, wav_path)

# Create DataLoader instances using collate_fn
train_loader_fusion = DataLoader(train_data_fusion, batch_size=32, shuffle=True, collate_fn=collate_fn)
test_loader_fusion = DataLoader(test_data_fusion, batch_size=32, shuffle=False, collate_fn=collate_fn)

epc = 6

In [55]:
# Starting a fusion model instance
InstFusionM = FusionModel(wav_model,model).to(device)

In [56]:
fusion_optimizer = AdamW(InstFusionM.parameters(), lr=2e-5)

# Calculate total steps and then take 10% for warmup
total_steps = len(train_loader_fusion) * epc
warmup_steps = int(0.08 * total_steps)

fusion_schedular = get_linear_schedule_with_warmup(
    fusion_optimizer,
    num_warmup_steps=warmup_steps,
    num_training_steps=total_steps
)

print(f"Total steps: {total_steps}, Warmup steps: {warmup_steps}")

Total steps: 972, Warmup steps: 77

In [57]:
# Loop to train and test through epochs
x = input().lower()
best_accuracy_fusion = 0.0
if x == 'y':
  start = timeit.default_timer()
  for t in range(epc):
      print(f"Epoch {t+1}\n-------------------------------")
      # Use the fusion DataLoader and train loop
      train_loop_fusion(train_loader_fusion, InstFusionM, fusion_optimizer, loss_fn, fusion_schedular)
      # Use the fusion DataLoader and test loop
      current_accuracy = test_loop_fusion(test_loader_fusion, InstFusionM, loss_fn)

      # Save best model
      if current_accuracy > best_accuracy_fusion:
          best_accuracy_fusion = current_accuracy
          torch.save(InstFusionM.state_dict(), f'best_model_weights_{best_accuracy_fusion:0.4f}.pth')
          print(f"Saved best model weights with accuracy: {(100*best_accuracy_fusion):>0.1f}%")

  print("Done!")
  end = timeit.default_timer()
  print(f"Total time taken: {end - start}")

y
Epoch 1
-------------------------------
loss: 1.528828  [   32/ 5167]
Test Error:
 Accuracy: 50.8%, Avg loss: 1.057095

Saved best model weights with accuracy: 50.8%
Epoch 2
-------------------------------
loss: 1.085492  [   32/ 5167]
Test Error:
 Accuracy: 62.9%, Avg loss: 0.822609

Saved best model weights with accuracy: 62.9%
Epoch 3
-------------------------------
loss: 0.766680  [   32/ 5167]
Test Error:
 Accuracy: 67.6%, Avg loss: 0.753725

Saved best model weights with accuracy: 67.6%
Epoch 4
-------------------------------
loss: 0.802242  [   32/ 5167]
Test Error:
 Accuracy: 67.9%, Avg loss: 0.751803

Saved best model weights with accuracy: 67.9%
Epoch 5
-------------------------------
loss: 0.659161  [   32/ 5167]
Test Error:
 Accuracy: 69.2%, Avg loss: 0.728951

Saved best model weights with accuracy: 69.2%
Epoch 6
-------------------------------
loss: 0.492350  [   32/ 5167]
Test Error:
 Accuracy: 69.1%, Avg loss: 0.733007

Done!
Total time taken: 500.18973836600026